version: '3.1'
services:
  app:
    build:
      context: .
    image: docker-xdebug-example:latest
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.0.75.1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=docker.dev"